### ISSUE TITLE
[TODO] Add MUI AppBar items to the AppBar

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/AgiliZenti#3]
I have added the initial AppBar to the top of the app and the imports necessary to complete the AppBar.

Some things will be necesary for the AppBar to be complete.  All of these are already imported to the App.js.

- [ ] Clicking on the Hamburger menu shouuld open a 200-250px wide drawer, using the MaterialUI <Drawer/>.
- [ ] Add a theme toggle switch as <Switch> next to the `<AccountCircle />` User Icon, which should eventually become an
  Avatar or replaced with the user photo when it gets uploaded.  Dark theme should be a black and gray.  Light theme should be    the native MUI blue and white until we can decide on a better light theme.
- [ ] Add a Menu to `<AccountCircle />` with `<Menu />`
- [ ] Add Tooltips to menu items and icons
- [ ] Add a Search field with <SearchIcon /> 
- [ ] Users will receive a notification through a Bell icon about new and/or completed tasks.
      Add a bell notifications Icon using `<NotificationsIcon />` with a  red `<Badge />` with the notification count.

**Additional context**
Some of App.js may need to be changed so it is a export default function App {...}.

AppBar could become its own component in /src/components

Note: You can possibly move whatever item to its own issue by clicking on the circle that appears when you hover over the item with t the checkbox in this issue to extract that to its own issue and can be assigned  separately.

**References**
https://mui.com/material-ui/react-app-bar/
https://mui.com/material-ui/api/app-bar/
